name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # [Optional] Build your static site here
      # Example for MkDocs:
      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.8'
      # - name: Install dependencies
      #   run: pip install mkdocs
      # - name: Build site
      #   run: mkdocs build

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1

      # If you are not using a static site generator, copy your static files to 'site/'
      - name: Prepare site directory
        run: |
          mkdir -p site
          cp README.md site/ 2>/dev/null || true
          cp PROJECT_SUMMARY.md site/ 2>/dev/null || true
          cp LICENSE site/ 2>/dev/null || true
          cp *.html *.css *.js site/ 2>/dev/null || true
          cp -r assets site/ 2>/dev/null || true
          # Add more copy commands as needed for your static content

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
